language: python
cache: pip
python:
  - '3.7'
  - '3.8'
  - '3.9'
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pylama chargeamps
  - poetry run isort --check chargeamps
  - poetry run black --check chargeamps
notifications:
  email: false
before_deploy:
  - pip install --upgrade pip
  - pip install poetry
  - poetry config pypi-token.pypi $PYPI_PASSWORD
  - poetry build
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
